[package]
name = "discord_bot"
version = "0.1.0"
authors = ["meruem"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
reqwest ="0.10.8"
openssl = { version = "0.10", features = ["vendored"] }